coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - app/
      carryforward: true
    - name: frontend
      paths:
        - resources/js/
      carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
